# Generated by Django 3.2.2 on 2021-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Arial', 'Arial'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana')], default='Times New Roman', max_length=25)),
                ('font_size', models.IntegerField(default=25)),
                ('font_color', models.CharField(choices=[('red', 'Czerwony'), ('black', 'Czarny'), ('orange', 'Pomarańczowy'), ('green', 'Zielony')], default='Czarny', max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
