# Generated by Django 3.2.2 on 2021-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bar', 'Słupkowy'), ('line', 'Liniowy'), ('pie', 'Kołowy')], default='Liniowy', max_length=10)),
                ('x_label', models.CharField(default='x', max_length=25)),
                ('y_label', models.CharField(default='y', max_length=25)),
                ('background_color', models.CharField(choices=[('red', 'Czerwony'), ('black', 'Czarny'), ('orange', 'Pomarańczowy'), ('green', 'Zielony')], default='Przezroczysty', max_length=10)),
            ],
        ),
    ]
