# Generated by Django 3.2.2 on 2021-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_app', '0002_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='chart',
            name='background_color',
            field=models.CharField(choices=[('red', 'Czerwony'), ('black', 'Czarny'), ('orange', 'Pomarańczowy'), ('green', 'Zielony'), ('transparent', 'Przezroczysty')], default='transparent', max_length=15),
        ),
        migrations.AlterField(
            model_name='text',
            name='font_color',
            field=models.CharField(choices=[('red', 'Czerwony'), ('black', 'Czarny'), ('orange', 'Pomarańczowy'), ('green', 'Zielony')], default='black', max_length=20),
        ),
    ]
