# Generated by Django 3.2.2 on 2021-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_app', '0003_auto_20210523_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surrname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='visibility',
            name='table_type',
            field=models.CharField(default='table', max_length=20),
        ),
    ]
