# Generated by Django 3.2.2 on 2021-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_app', '0006_auto_20210605_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visibility',
            old_name='table_type',
            new_name='data_type',
        ),
        migrations.AddField(
            model_name='text',
            name='data_type',
            field=models.CharField(default='text', editable=False, max_length=5),
        ),
    ]
