# Generated by Django 3.2.2 on 2021-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_app', '0007_auto_20210605_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='type',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='x_label',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='y_label',
        ),
        migrations.AddField(
            model_name='chart',
            name='data_name',
            field=models.CharField(default='tekst', error_messages={'unique': 'Zarejstrowano taka nazwe'}, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='data_value',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
